; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5C6C9609-4F6D-467C-8B0B-02A4748007BA}
AppName=Wazzapp
AppVersion=1.0.1
;AppVerName=Wazzapp 1.0.1
AppPublisher=Itai Shek
AppPublisherURL=https://github.com/ItaiShek/Wazzapp
AppSupportURL=https://github.com/ItaiShek/Wazzapp
AppUpdatesURL=https://github.com/ItaiShek/Wazzapp
#define SourceBaseDir "{src}\..\..\Wazzapp"
DefaultDirName={autopf}\Wazzapp
SetupIconFile="{#SourceBaseDir}\icon.ico"
UninstallDisplayIcon="{app}\Wazzapp.exe"
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
; PrivilegesRequired=lowest
OutputBaseFilename=WazzappInstaller
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#SourceBaseDir}\build\Release\Wazzapp.exe"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Registry]
; ➤ Add context menu when right-clicking ON a folder
Root: HKCU; Subkey: "Software\Classes\Folder\shell\OpenWithWazzapp"; ValueType: string; ValueName: ""; ValueData: "Fix all jpeg images in the directory with Wazzapp"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Folder\shell\OpenWithWazzapp"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\Wazzapp.exe"""
Root: HKCU; Subkey: "Software\Classes\Folder\shell\OpenWithWazzapp\command"; ValueType: string; ValueName: ""; ValueData: """{app}\Wazzapp.exe"" ""%1"""

; ➤ Add context menu when right-clicking INSIDE a folder (background space)
Root: HKCU; Subkey: "Software\Classes\Directory\Background\shell\OpenWithWazzapp"; ValueType: string; ValueName: ""; ValueData: "Fix all jpeg images in the directory with Wazzapp"; Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\Classes\Directory\Background\shell\OpenWithWazzapp"; ValueType: string; ValueName: "Icon"; ValueData: """{app}\Wazzapp.exe"""
Root: HKCU; Subkey: "Software\Classes\Directory\Background\shell\OpenWithWazzapp\command"; ValueType: string; ValueName: ""; ValueData: """{app}\Wazzapp.exe"" ""%V"""

[Icons]
Name: "{autoprograms}\Wazzapp"; Filename: "{app}\Wazzapp.exe"; IconFilename: "{app}\Wazzapp.exe"
Name: "{autodesktop}\Wazzapp"; Filename: "{app}\Wazzapp.exe"; Tasks: desktopicon; IconFilename: "{app}\Wazzapp.exe"
Name: "{usersendto}\Wazzapp (fix WhatsApp jpeg images for Photoshop)"; Filename: "{app}\Wazzapp.exe"; IconFilename: "{app}\Wazzapp.exe"